common/src/main/scala/com/gu/salesforce/Salesforce.scala
common/src/main/scala/com/gu/salesforce/SalesforceService.scala
common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
common/src/test/scala/com/gu/salesforce/Fixtures.scala
common/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
common/src/test/scala/com/gu/salesforce/SerialisationSpec.scala
project/Dependencies.scala

Instead use the issued_at time of the token to check whether we should refresh it or not.
This simplifies the logic and also allows us to remove Akka from the project. 
To handle the concurrency & mutable state I'm using [ScalaSTM](https://nbronson.github.io/scala-stm/) which is really nice.

Replace the scheduled Salesforce Auth token fetch

---

README.md
build.sbt
common/src/main/scala/com/gu/helpers/WebServiceHelper.scala
common/src/test/java/com/gu/test/tags/annotations/IntegrationTest.java
common/src/test/scala/com.gu.config/ConfigSpec.scala
common/src/test/scala/com/gu/salesforce/SalesforceSpec.scala
common/src/test/scala/com/gu/test/tags/objects/IntegrationTest.scala
common/src/test/scala/com/gu/zuora/SerialisationSpec.scala
common/src/test/scala/com/gu/zuora/ZuoraSpec.scala
monthly-contributions/src/main/scala/com/gu/support/workers/encoding/CreatePaymentMethodStateDecoder.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CirceEncodingBehaviourSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreatePaymentMethodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateSalesforceContactDecoderSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateSalesforceContactSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/SendThankYouEmailSpec.scala
project/Dependencies.scala
project/Settings.scala

There are a number of integration tests in the project which talk to real services, these are very useful for real end to end testing, but slow to run and prone to failures if any of the services are playing up.
This PR adds a ScalaTest tag and annotation 'IntegrationTest' which can be applied to individual tests (the tag) or whole specs (the annotation) to stop them running when the sbt test command is invoked; it also tags the appropriate tests/specs with these tags.

Create a Scalatest tag for integration tests

---

common/src/main/scala/com.gu.okhttp/package.scala
common/src/main/scala/com/gu/helpers/Retry.scala
common/src/main/scala/com/gu/paypal/PayPalService.scala
common/src/main/scala/com/gu/stripe/Stripe.scala
common/src/main/scala/com/gu/stripe/StripeService.scala
common/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala

Log errors as warnings elsewhere.
Also renamed Stripe.Error to StripeError as it is clearer in Sentry

Only log as error in the top level handler to avoid flooding Sentry

---

cloud-formation/src/lambdas/failureHandlerLambda.yaml
cloud-formation/src/state-machine-retries.yaml
cloud-formation/src/state-machine.yaml
common/src/main/scala/com/gu/emailservices/EmailService.scala
common/src/main/scala/com/gu/emailservices/EmailServicesConfig.scala
common/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
common/src/test/scala/com.gu.config/ConfigSpec.scala
docs/error-handling.md
monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateCodecs.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ServicesHandler.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreatePaymentMethodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreatePaymentMethodStateDecoderSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateSalesforceContactDecoderSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateSalesforceContactSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CreateZuoraSubscriptionSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/FailureHandlerSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/LambdaSpec.scala
project/Dependencies.scala

Add a failure handler state to the monthly contribution sign up step function. 
This handler will deal with sign ups that have permanently failed, for instance due to card payment failures, by emailing the user to inform of the failure.
Note that we do not invoke this handler if the 'Thank you' email fails because the sign up will have already succeeded by this point.

Failure handler

---

README.md
common/src/main/resources/application.conf

Currently support-workers and support-frontend both have a private conf file called support.private.conf which means that it is difficult to work on them both locally as the conf files either overwrite each other or have to be merged
[Trello card here](https://trello.com/c/kMjYGnXa/649-rename-private-conf-file-for-support-projects-to-allow-local-development-on-both-projects)

Rename the private conf file

---

common/src/main/scala/com/gu/support/workers/encoding/Encoding.scala
common/src/main/scala/com/gu/support/workers/encoding/Encryption.scala
common/src/main/scala/com/gu/support/workers/encoding/Wrapper.scala
common/src/main/scala/com/gu/support/workers/encoding/package.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Conversions.scala
monthly-contributions/src/test/scala/com/gu/support/workers/EndToEndSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/LambdaSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/PayPalErrorsSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/UpdateMembersDataAPISpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/UpdateMembersDataAPISpec.scala
project/Dependencies.scala

AWS Step Functions expect to be passed valid Json, as we want to encrypt the whole of the
state, we need to Base64 encode it and then wrap it in a Json 'wrapper' object.
This PR does that and then fixes all the tests

Json wrapper

---

cloud-formation/src/cfn-template.yaml
common/src/main/scala/com/gu/support/workers/encoding/Encoding.scala

Add a CloudFormation policy to allow support-workers to access the KMS key

Add KMS key ARNs to CloudFormation

---

cloud-formation/src/lambdas/createZuoraSubscriptionLambda.yaml
common/src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala
common/src/main/scala/com/gu/zuora/ZuoraService.scala
common/src/main/scala/com/gu/zuora/model/QueryData.scala
common/src/main/scala/com/gu/zuora/model/response/QueryResponse.scala
common/src/main/scala/com/gu/zuora/model/response/Responses.scala
common/src/main/scala/com/gu/zuora/model/response/SubscriptionsResponse.scala
common/src/test/scala/com/gu/zuora/EncoderSpec.scala
common/src/test/scala/com/gu/zuora/Fixtures.scala
common/src/test/scala/com/gu/zuora/SerialisationSpec.scala
common/src/test/scala/com/gu/zuora/ZuoraSpec.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala

The subscribe call to Zuora is not idempotent and it is possible for the request to time out (from the point of view of the step functions) whilst actually still succeeding in Zuora. This would result in us retrying and potentially creating multiple live subscriptions.
To get around this problem I have introduced a check to the CreateZuoraSubscription lambda so that if an existing monthly recurring subscription exists for the current user then we skip the account creation step and just move on to the next step in the monthly contribution flow.
[**Trello Card**](https://trello.com/c/1i1MhfIh/615-q2-test-2-check-for-existing-monthly-contribution-before-attempting-zuora-subscribe-call)

Check for an existing contribution subscription before creating a new one

---

common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
project/Dependencies.scala

Since we started wrapping the handler state to enable encryption, the error entity added to the input json by aws is now a level above the handler state so not available to the handler. Since we were only using it for logging anyway I've just removed the logging that was causing the problem.

FailureHandler was failing to handle failures

---

cloud-formation/src/environment-variables.yaml

So that all the lambdas load the correct config

Provide the stage to lambdas as an environment variable

---

cloud-formation/src/cfn-template.yaml

Lambdas don't currently have the cloudwatch:putMetricData permission which is causing failures

Add cloudwatch:putMetricData permission to the Lambda execution role

---

common/src/main/scala/com/gu/stripe/Stripe.scala
monthly-contributions/src/test/scala/com/gu/support/workers/CirceEncodingBehaviourSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala

Stripe errors were not being parsed correctly, so the default RetryUnlimited was being applied to all stripe errors.
I've tested this change on CODE, and it correctly fails immediately for invalid_request_error.

Fix stripe error parsing

---

cloud-formation/src/cfn-template.yaml
cloud-formation/src/lambdas/contributionCompletedLambda.yaml
cloud-formation/src/lambdas/createZuoraSubscriptionLambda.yaml
cloud-formation/src/state-machine.yaml
monthly-contributions/riff-raff.yaml
monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateCodecs.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ContributionCompleted.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
monthly-contributions/src/test/scala/com/gu/support/workers/EndToEndSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/ContributionCompletedSpec.scala
project/Dependencies.scala

Adding an extra step so that support-frontend can notify the user when the transaction has succeeded.  This is as soon as the Zuora step completes, since at this point the user will be billed.

Add complete state

---

cloud-formation/src/state-machine.yaml

Add an extra step to the state machine that delays the end of the execution by 30 seconds.  This is to avoid the situation where the state machine is terminated before the client's polling detects that the execution is complete.  This could happen during a deployment, when a new state machine is created and the old is terminated.

Add a wait state

---

common/src/main/scala/com/gu/stripe/Stripe.scala
common/src/test/scala/com/gu/zuora/Fixtures.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala

The monthly contributions flow currently fails if the user attempts to pay with American Express, because Zuora requires the card type to be sent as 'AmericanExpress', not 'American Express'.
See also:
https://github.com/guardian/membership-common/pull/371
[**Trello Card**](https://trello.com/c/lrELOTgh/810-fix-american-express)
* Remove whitespace when creating CreditCardReferenceTransaction for Zuora
cc @davidfurey @rupertbates

Fix for American Express

---

common/src/main/resources/application.conf
common/src/main/scala/com/gu/zuora/ZuoraConfig.scala
common/src/main/scala/com/gu/zuora/ZuoraService.scala
common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
common/src/main/scala/com/gu/zuora/model/response/Responses.scala
common/src/test/scala/com/gu/salesforce/Fixtures.scala
common/src/test/scala/com/gu/zuora/Fixtures.scala
common/src/test/scala/com/gu/zuora/SerialisationSpec.scala
common/src/test/scala/com/gu/zuora/ZuoraSpec.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
monthly-contributions/src/test/scala/com/gu/support/workers/DefaultBillingPeriodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala
project/Dependencies.scala

To enable us to bill supporters annually as well as monthly.
* This change depends on [this PR](https://github.com/guardian/support-models/pull/13) in support-models. It is backwardly compatible with the existing version of support-frontend, because any request received which does not specify the billing period will default to Monthly.
* This change requires updates to support-worker private conf 
[**Trello Card**](https://trello.com/c/qF6I86xx/878-uk-annual-contributions)

Annual contributions

---

cloud-formation/src/view.yaml

Failure handler seems to need more memory when there is a payment
failure

Increase failure handler memory quota

---

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala

@pvighi noticed that we were passing the wrong parameter into the 'allow Guardian mail' field in Salesforce, this PR fixes it.
[**Trello Card**](https://trello.com/c/Rr3cbepP/902-fix-mail-permissions-in-support-workers)

Pass the correct parameters into the Salesforce upsert

---

common/src/main/scala/com/gu/support/workers/encoding/Encoding.scala
common/src/main/scala/com/gu/support/workers/encoding/Encryption.scala
common/src/main/scala/com/gu/support/workers/encoding/Wrapper.scala
common/src/main/scala/com/gu/support/workers/lambdas/Handler.scala
common/src/main/scala/com/gu/zuora/ZuoraConfig.scala
common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
common/src/test/scala/com/gu/encryption/EncryptionSpec.scala
common/src/test/scala/com/gu/zuora/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Conversions.scala
monthly-contributions/src/test/scala/com/gu/support/workers/EndToEndSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
project/Dependencies.scala

To make it easier to switch encryption on and off without a risk of support-frontend and support-workers getting out of sync, this PR moves the setting which determines whether a request is encrypted or not into the request state rather than the config setting.
This means that support-frontend is now the only place where we need to update the encryption setting and support-workers will handle whatever it is sent. This would also allow us to send a mix of encrypted and unencrypted requests if for instance we wanted to keep test user requests unencrypted
Depends on PR https://github.com/guardian/support-models/pull/17
[**Trello Card**](https://trello.com/c/PxnJi97v/948-switch-on-encryption-in-the-support-stack)

Take encryption settings from the request state, not config

---

common/src/main/scala/com/gu/emailservices/EmailService.scala

Whilst investigating how to customise the thank you email for US contributors I noticed that the data which we pass through to ExactTarget was not being recorded correctly. 
The reason for this was that the json structure we were sending was incorrect, this PR fixes it.
[**Trello Card**](https://trello.com/c/KnSMJIka/761-update-thank-you-email-to-allow-us-to-send-different-copy-to-us-and-uk-and-row-contributors)

Correct the email payload which we send to ExactTarget

---

common/src/main/scala/com/gu/monitoring/products/RecurringContributionsMetrics.scala
monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ContributionCompleted.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala

There are currently a small number of cloudwatch metrics sent by this application under the "support-worker" namespace. This change adds some more.
The reason for these new metrics is so that I create some composite metrics in a tool called "librato" that will calculate the ratio of successful completions of monthly payments to number of payments attempted and trigger an alert if this falls below a particular rate.
Why here when there are lambda metrics and state-machine metrics in AWS already?
1) It is not currently possible to import metrics under the "state" namespace into Librato. They are just not recognised.
2) Should this change, there is still a problem with the metrics in the "state" namespace. Their metric name includes a versioning id. This changes each time a new version is …

adds cloudwatch metrics for each lambda function

---

common/src/main/scala/com/gu/monitoring/products/RecurringContributionsMetrics.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ContributionCompleted.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala

Reverts guardian/support-workers#68
This is reverting a change that added extra cloudwatch metrics to our Lambda functions.
This was so that we could take advantage of the composite metrics and alerting in Librato tocreate alerts on the rates of success vs attempts on out Lambda functions.
The new metrics were necessary because the full complement of tags for the standard AWS Lambda metrics were not being pulled through by Librato - as a result they were missing critical data.
Librato has just informed me that they have managed to fix this bug and I have tested and confirmed that all tags for the standard AWS Lambda metrics are now pulling through.
As a result the duplicate metrics are no longer needed and can be removed (no sense paying for something we already have).

Revert "adds cloudwatch metrics for each lambda function"

---

project/plugins.sbt

1. To keep things up to date 
2. Because this version of the plugin seems to ensure that tests are passing before uploading to S3, and we had a problem before where riff-raff would deploy a build, even if the tests on master were red - so this gives us some additional safety.
* Update plugin
I can deploy this branch to CODE, and I'm assuming that's the only testing required for this.

Use latest riff-raff plugin

---

cloud-formation/src/templates/cfn-template.yaml

This PR adds two new alarms, so that we know if things are broken in production:
**1. NoStateMachineExecutionsAlarm**
Intended to catch cases where the interaction between support-frontend and support-workers is fundamentally broken.
**2. ExecutionFailureAlarm** 
If the Fail State added in https://github.com/guardian/support-workers/pull/77 is triggered, we should be informed so that we can fix the bug (or add more genuine/valid reasons for failure to the handler).
If we break any of the individual lambdas, this should serve as a catch all for that too.
[**Trello Card**](https://trello.com/c/cnYz9x3R/1115-add-basic-production-monitoring-to-support-projects)
* Add new alarms to Cloudformation
cc @michaelwmcnamara

Add alarms for no executions and failed executions

---

cloud-formation/src/templates/retries.yaml

Recently one of our lambdas failed due to an AWS Service exception. Because the [existing retry logic](https://github.com/guardian/support-workers/blob/master/cloud-formation/src/templates/retries.yaml) only handles custom exceptions (which are generated by our own code), we did not retry the task execution. 
Similarly, if an exception is thrown before the handler is invoked (e.g. if AWS cannot find the handler function at all), or if a Lambda times out, our current logic would fail to trigger retries.
This PR adds a catch-all for these cases, based on the [AWS documentation](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html).
As far as I can tell this works like a pattern match in Scala, so the generic retry rule is only reached if the more specific errors …

Handle external errors which could occur during State Machine executions

---

cloud-formation/src/templates/retries.yaml

The catch-all retry case I added [here](https://github.com/guardian/support-workers/pull/82) means that we are repeatedly retrying when we throw a com.gu.support.workers.exceptions.RetryNone.
This PR stops us from doing that.
cc @davidfurey @rupertbates

Explicitly set retries to 0 for RetryNone

---

common/src/main/scala/com/gu/stripe/Stripe.scala
common/src/main/scala/com/gu/stripe/StripeService.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
project/Dependencies.scala

Goal: Be able to test out a newer version of Stripe app by app to remove the element of blind courage currently required to update the version in the Stripe dashboard.
[The Stripe Upgrade Guide](https://stripe.com/docs/upgrades) specifies that the API version used for a given stripe account is the one configured in the dashboard, unless the request has a Stripe-Version header. So, the plan is to send a header Stripe-Version -> 2017-08-15 for the GNM membership account in each relevant app and then up the version in the dashboard.
This change makes it possible to add a stripe version to the config that will be sent on each request to Stripe. 
Additionally, since version [2015-02-18](https://stripe.com/docs/upgrades#2015-02-18), the call to create a customer returns not a list of `cards` …

Send a Stripe-Version header if configured and expect the new Customer model from Stripe

---

cloud-formation/src/templates/state-machine.yaml

Members-data-api now reads directly from Zuora in order to determine a user's attributes. This means that we don't need to trigger a population of the Dynamo table (which the api used to read attributes from) as part of the sign-up flow, so this is a redundant task. It also seems to be one of the most unreliable lambdas in the project, so removing it also provides some reliability benefits.
Note that this is only the first part of this work. It removes the task from the state machine, but leaves the lambda (and related code) in place. This will be removed in a later PR, but needs to stay around when this is merged so that all running executions can complete (without error).
[**Trello Card**](https://trello.com/c/yqxk9rO8/1050-remove-updatemembersdataapi-lambda-from-support-workers)
* …

Remove members-data-api step (part 1)

---

common/src/main/scala/com/gu/zuora/model/response/Responses.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala

We were unable to sign-up new users during a recent [Zuora incident](https://trust.zuora.com/incidents/0yd5tp9k6z10). This PR allows us to cope with the specific problem that we saw (by retrying), should it happen again. 
There are probably a number of other cases that we should consider handling too, but at the moment I can't find any documentation which clearly details all of the expected errors. I'll open a support ticket to ask about this and then open new PRs if necessary.
[**Trello Card**](https://trello.com/c/lSpMrPhN/1211-add-retries-for-known-zuora-errors-which-occur-during-the-createzuorasubscription-task)
* Add pattern match to catch 'UNKNOWN_ERROR', and convert to a RetryUnlimited.
* Add Zuora-specific test cases to ErrorHandlerSpec.

Retry on UNKNOWN_ERROR from Zuora

---

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala

At the moment the FailureHandler does not capture all card errors, and this recently led to a false alarm.
[**Trello Card**](https://trello.com/c/2W4yxBW9/1225-cope-with-a-larger-set-of-card-errors-in-failurehandler)
* Catch all errors of type 'card_error' in the pattern match, instead of looking for specific card failure codes.

Cope with all card errors in FailureHandler

---

common/src/main/scala/com/gu/salesforce/Salesforce.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala

We hit some rate limiting errors from Salesforce this morning: 
```Received response code: 403 | response body: [{"message":"TotalRequests Limit exceeded.","errorCode":"REQUEST_LIMIT_EXCEEDED"}]```
This is not explicitly handled, and therefore caused us to fail several executions.
To some extent adding retries here will exacerbate the problem, but I think the back-off rule means that the impact on our overall limits will not be too significant. I also notice that this is the approach we take for Stripe rate-limiting, so I suggest that we follow the same pattern here.
* Treat REQUEST_LIMIT_EXCEEDED error as a RetryUnlimited

Retry if we hit Salesforce rate limiting errors

---

README.md
build.sbt
project/Dependencies.scala
project/Settings.scala

With the current SBT configuration it is hard to run the integration tests from the command line because they are excluded by default to prevent them failing on TeamCity (it doesn't have the necessary credentials to run them).
This PR adds a new `IntegrationTest` configuration which allows us to run `sbt test` to run only unit tests or `sbt it:test` to run all tests including integration tests
[**Trello Card**](https://trello.com/c/4Oz8P5MI/1234-find-a-way-to-avoid-running-integration-tests-on-teamcity-for-support-workers)

Split unit tests and integration tests more effectively

---

common/src/main/scala/com/gu/zuora/model/response/Responses.scala
docs/error-handling.md
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala

This is a follow up to https://github.com/guardian/support-workers/pull/89. This should allow us to cope with all retry-able errors that we might receive from Zuora.
[**Trello Card**](https://trello.com/c/lSpMrPhN/1211-add-retries-for-zuora-errors-which-occur-during-the-createzuorasubscription-task)
* Add more known errors to the asRetryException pattern match (and test them)
* Update error handling docs

Improve Zuora error handling

---

common/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
monthly-contributions/src/test/scala/com/gu/support/workers/errors/ErrorHandlerSpec.scala

We recently failed to sign up a user during a period of Salesforce downtime. This is because we treated the [exception](https://sentry.io/the-guardian/support-workers/issues/457711827/) as a RetryLimited, rather than a RetryUnlimited. In my opinion we should treat SocketExceptions in the same way that we treat SocketTimeoutExceptions, with respect to retries. 
* Add explicit handling for SocketExceptions

Handle SocketExceptions

---

project/Dependencies.scala

To keep support-internationalisation as up to date as possible.
* `Dependencies.scala`

Upgrade support-internationalisation

---

common/src/main/scala/com/gu/emailservices/EmailService.scala

This is a follow up to https://github.com/guardian/support-workers/pull/102.
[**Trello Card**](https://trello.com/c/Fh3vvzo7/1296-add-retries-to-cope-with-cases-where-failurehandler-throws-lambdaunknown-errors)
* Log the result when sending a message to SQS

Add more logging to the email service

---

cloud-formation/src/build-cfn.js
cloud-formation/src/templates/emailRetries.yaml
cloud-formation/src/templates/state-machine.yaml

This PR makes it more likely that users who fail to sign-up will receive an email. It should also cut down on the noise from our AWS alerts, as currently if this lambda fails we get an alert due to the Step Function execution failing.
I've set up some temporary alerting on the two lambdas which are timing out, so that I can continue debugging this without spamming a huge mailing list. (Full details on approach can be found in the Trello card).
This PR also makes us slightly more conservative about retrying the lambda which sends users a thankyou email - at worst we will now send them two emails, whereas before we could have introduced a bug which would have led to us spamming users for up to 24 hours.
Some docs on task retries can be found here: …

Change retry rules for lambdas which send an email

---

monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala

Currently if decoding fails in the decode.sh script we don't get any diagnostic information, this PR changes that.

Handle decoding errors better in the decoder.sh script

---

common/src/main/scala/com/gu/aws/AWSAsyncHandler.scala
common/src/main/scala/com/gu/emailservices/EmailService.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala

Because I still can't debug the email task timeouts...
[**Trello Card**](https://trello.com/c/Fh3vvzo7/1296-stop-failurehandler-from-throwing-lambdaunknown-errors)
* Add logging to AWSAsyncHandler, so we can ascertain whether we get a response from AWS
* Move from onComplete to recover/map, to ensure that the email service logging completes before the lambda exits
* EmailService class now accepts an execution context

Add even more logging to help understand task timeouts

---

common/src/main/scala/com/gu/threadpools/CustomPool.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala

Since we're running in a lambda with relatively limited resources, the max number of threads available (when using the global execution context) is always likely to be pretty low. We think that the lambda timeouts that we're seeing may be due to thread contention, so this PR attempts to test that theory.
[**Trello Card**](https://trello.com/c/Fh3vvzo7/1296-stop-failurehandler-from-throwing-lambdaunknown-errors)
* Configure new execution context with fixed thread pool
* Log the number of available processors to help with debugging (see https://docs.scala-lang.org/overviews/core/futures.html#the-global-execution-context)

Configure thread pool for thank you email lambda

---

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

Following on from https://github.com/guardian/support-workers/pull/111, we want to send the query parameters field to ophan
@guardian/contributions

Send query parameters in ophan event

---

README.md
build.sbt
common/src/main/resources/application.conf
common/src/main/scala/com/gu/stripe/StripeService.scala
common/src/test/scala/com.gu.config/ConfigSpec.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
scripts/decode.sh

Currently when a user signs up with a credit card we send their Identity ID in the description field when creating the Stripe customer record. For GDPR reasons we need to stop doing this.
I have tested this on code and it works without any changes to support-frontend so can be released first.
[**Trello Card**](https://trello.com/c/rNWSgTCY/1363-investigate-data-sent-to-stripe)

Remove identityid from stripe

---

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala

We are not currently waiting for the asynchronous call which puts an email message onto an SQS queue. This means that the handler can exit before we've confirmed that the result from AWS was successful.
Although we wait for a Future to complete [here](https://github.com/guardian/support-workers/blob/980394a0e8a2f112a30bb5069af1a160c6a8d694/common/src/main/scala/com/gu/support/workers/lambdas/Handler.scala#L46-L51), we have ended up with nested Futures and were discarding the one that we care about on line 33.
We will have failed to send thank you emails to some recurring contributors since this issue was introduced.

Wait for email result before allowing handler to exit

---

common/src/main/scala/com/gu/salesforce/Salesforce.scala

To make it easier to debug issues with Salesforce authentication.
* Override getMessage for SalesforceAuthenticationErrorResponse so that we get a useful error [here](https://github.com/guardian/support-workers/blob/baa1d6787a819a8100c7e20a4b56fe73d5f3b9c8/common/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala#L21).

Pass through SF auth errors

---

common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala
monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
monthly-contributions/src/test/scala/com/gu/support/workers/LambdaSpec.scala
monthly-contributions/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

We recently had [a bug](https://github.com/guardian/support-workers/pull/116) which resulted from the SendThankYouEmail lambda exiting with an incomplete future pending. 
This partly came about because it returns `Unit` so it was easy to miss that we hadn't completed an operation. By changing the return type to the value that is returned by the future we make any recurrence of this less likely.

Return a value from the SendThankYouEmail lambda

---

cloud-formation/src/templates/state-machine.yaml

We recently saw a failed execution due to a _Lambda.AWSLambdaException_ being thrown during the ContributionCompleted task. As there were no retries configured for this lambda, this caused the whole state machine execution to fail, and we incorrectly reported a failure to the client (even though the payment had been taken).
* Add the default retries block (which includes a [catch all](https://github.com/guardian/support-workers/blob/master/cloud-formation/src/templates/retries.yaml#L15-L19) for this type of exception) to the ContributionCompleted lambda

Add retries for ContributionCompleted lambda

---

src/main/resources/application.conf
src/test/scala/com/gu/support/workers/Fixtures.scala
src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala
src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala

* I noticed that the private config files currently contain all the Zuora product ids which could be public so I've moved them to the public config to simplify things.
* I also noticed that the `CreateZuoraSubscriptionSpec` tests are not currently testing anything because there is code in ZuoraService to prevent multiple recurring contributions with the same Identity id. To get round this I have mocked the method which checks for a subscription to always return `None`

Config fix

---

src/main/scala/com/gu/support/workers/encoding/StateCodecs.scala
src/test/scala/com/gu/support/workers/Fixtures.scala
src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala

The FailureHandler needs to cope with old and new versions of the Json schema.
This lambda can serve as a catch for the CreatePaymentMethod lambda (which already handles both schemas), meaning that it can receive the input state as sent from support-frontend (as per: https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultpath.html#input-output-resultpath-catch).
* Add a fixture/test for the the old schema.
* Re-factor old/new schema handling into helper function and use it for CreatePaymentMethod and FailureHandler states.
* Remove the createPaymentMethodState encoder, because I don't think we actually use it anywhere?

Fix the failure handler

---

cloud-formation/src/templates/state-machine.yaml

Instead of using a lambda, we now use a [Pass State](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-pass-state.html) to indicate success. This means that we don't need to worry about schema changes in the future (more details on why this is bad here: https://github.com/guardian/support-frontend/pull/811). 
This change should also speed up executions / in-browser feedback as users will never have to wait for a superfluous lambda to run (or cold start).
It also allows us to remove the ContributionCompleted lambda function - as far as I can tell this just logs and produces JSON output to indicate success. I'll do that in a separate PR for the reasons detailed here: https://github.com/guardian/support-workers#deployment
* Use a pass state instead of a lambda to …

Use pass state as indicator for checkout success

---

src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

Previously, when running the `acquisitions` job in the excavator, we relied on joining on the `pageview` table to get the `identity id` for recurring contributions. Seeing as it is available here, we should send it through, lessening our dependence on the `pageview` table.
@guardian/contributions

Send identity id through in acquisition event

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

So exact target can send thank you emails tailored to frequency i.e. annual and monthly contributions. 📨
[**Trello Card**](https://trello.com/c/6qGb9bHv/751-validate-monthly-and-annual-email-confirmations)
* Adds product field to ContributionEmailFields class
* Sets value using `state.product.billingPeriod` which will result in: `Monthly-contribution` or `Annual-contribution`being passed through. 
* Updates test objects to include product field.

set product in email fields

---

cloud-formation/src/templates/cfn-template.yaml

Currently a state machine failure is broadcast to all of reader revenue dev.
This is overkill as 2/3's of recipients are not going to take any action on the alert.
Moreover this increases the risk of developers "tuning out" AWS alerts as a result of them being frequent and not relevant to their immediate area of responsibility.
The plan going forward is to send alerts that are not time critical to the specific team of responsibility, reserving the reader.revenue.dev email address for time critical "everything is on fire!" style alerts - where we want action to be taken by the first person to see the alert.

send alerts to simple-dev only

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
src/main/scala/com/gu/emailservices/EmailFields.scala
src/main/scala/com/gu/emailservices/FailedContributionEmailFields.scala
src/main/scala/com/gu/emailservices/FailedDigitalPackEmailFields.scala
src/main/scala/com/gu/salesforce/Salesforce.scala
src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
src/test/scala/com/gu/emailservices/EmailFieldsSpec.scala
src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala
src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala

Add sfContactId and Identity userId to the email payload.  The messages are consumed by membership-workflow which triggers the emails. In Braze emails we upsert users using the sfContactId as the primary key. membership-workflow can resolve the sfContactId from the identity user id
We are migrating from our CMT providers, from ET to Braze

Add sfContactId to Email payload

---

cloud-formation/src/templates/cfn-template.yaml
src/main/resources/application.conf
src/main/scala/com/gu/config/Configuration.scala
src/main/scala/com/gu/emailservices/EmailService.scala

We need to be able to configure CODE to use the CODE queues. This is necessary for testing Braze emails sent by membership-workflow in CODE.
* configurable thank you email queue name

configurable thank you email queue name

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

The service email templates will render content depending on payment type
Add payment method name to SubscriberAttributes sent to Exact Target and Braze. These are used by the email templates.

send payment type to email send sqs queue

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala

Work done:
Change payment provider names rendered on Braze email templates
Why are we doing this?
Changes requested by CMT migration team

update payment provider template fields

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala

We want to display the currency identifier on the recurring contributor email
Use currency identifier rather than gyph, sent to CMT provider which sends emails

use currency identitier rather than just the gyph

---

build.sbt

https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31507
We are pulling in old versions of jackson-databind primarily via aws-sdks. It's suggested [here](https://github.com/aws/aws-sdk-java) that this shouldn't be a breaking change for the aws sdks, and indeed when I tested it on CODE, it wasn't. I bumped the version, signed in with a test user, then signed up for a recurring contribution that succeeded. I then also tried with a stripe card that I knew should fail. I checked that the executions of the state machines behaved as expected, and that a subscription was set up in Zuora for the happy case, and that it wasn't on expected error. 
Any other suggested checks?
[**Trello Card**](https://trello.com) // none. Inspired by Snyk.
* Bumped jackson-databind and jackson-annotations to …

Bump jackson-databind version and jackson-annotations to 2.9.7

---

build.sbt

[https://app.snyk.io/vuln/SNYK-JAVA-ORGBEANSHELL-72452](https://app.snyk.io/vuln/SNYK-JAVA-ORGBEANSHELL-72452)
Due to having an old version of dispatch, we had a dependency, specifically beanshell, which had the above security issue. 
I've tested putting through a recurring contribution on CODE and it works just fine.

Upgrade dispatch to 0.14.0

---

build.sbt
src/main/scala/com/gu/support/workers/GetRecurringSubscription.scala
src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala
src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
src/main/scala/com/gu/zuora/ZuoraService.scala
src/main/scala/com/gu/zuora/model/Account.scala
src/main/scala/com/gu/zuora/model/response/QueryResponse.scala
src/main/scala/com/gu/zuora/model/response/Responses.scala
src/main/scala/com/gu/zuora/model/response/SubscriptionsResponse.scala
src/test/scala/com/gu/support/workers/AccessScopeCodecTest.scala
src/test/scala/com/gu/support/workers/Fixtures.scala
src/test/scala/com/gu/support/workers/GetRecurringSubscriptionIsInAccessScopeSpec.scala
src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
src/test/scala/com/gu/support/workers/lambdas/CreateZuoraSubscriptionStateDecoderSpec.scala
src/test/scala/com/gu/zuora/Fixtures.scala
src/test/scala/com/gu/zuora/ZuoraSpec.scala

This PR is part of the series designed to deduplicate zuora subscriptions in case of browser side or step function repetitions.  I have already changed the models https://github.com/guardian/support-models/pull/43 and support frontend https://github.com/guardian/support-frontend/pull/1049
[**Trello Card**](https://trello.com/c/qaNYnBkp/87-npf-make-step-functions-check-form-visit-token-as-well-as-identity-id-for-preventing-duplicate-recurring-cont-from-the-same-page)
I have tested this in CODE but need to redo with the final approved code before shipping.

use the session id to decide which zuora accounts to deduplicate against

---

cloud-formation/src/templates/lambda.yaml

The lambda cold start time seems very slow.  The CPU allocation is related to the memory requested, so even though we need hardly any memory, we could increase the memory allocation in order to improve the cold starts.
I have increased from 0.5 to 1.5 gb because this is what the new product api has and it seems a lot quicker https://github.com/guardian/zuora-auto-cancel/blob/master/handlers/new-product-api/cfn.yaml#L122

faster cpu to improve cold start time

---

src/test/scala/com/gu/support/workers/AccountAccessScopeCodecTest.scala
src/test/scala/com/gu/support/workers/IsAccountAccessAllowedSpec.scala
src/test/scala/com/gu/support/workers/lambdas/CreateZuoraSubscriptionStateDecoderSpec.scala

@rupertbates [pointed out](https://github.com/guardian/support-workers/pull/147#pullrequestreview-168026962) that in my haste to fix the names of everything, I didn't check over the tests properly.  This PR sorts that out hopefully.

make the test names and descriptions sensible

---

cloud-formation/src/templates/cfn-template.yaml

I noticed that these alerts only go to S&C, but the Contributions team are also working on this app.
I'm assuming this is the most appropriate topic, based on: https://github.com/guardian/payment-api/blob/master/src/main/resources/cloud-formation.yaml#L529-L530

Notify contributions team about support-workers errors

---

src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

Currently this swallows the actual error messages when either the ophan or GA requests fail, because I didn't define the getMessage method

Define AnalyticsServiceErrorList.getMessage

---

src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

The GA id is mandatory but may not be provided by support-frontend. If not then generate one (as in [subscriptions-frontend](https://github.com/guardian/subscriptions-frontend/blob/bd9c63ea44330f05ca82afd774343fedb6cd3655/app/controllers/Checkout.scala#L304))

Generate a GA id if not provided

---

src/test/scala/com/gu/support/workers/Fixtures.scala

because we have zuora dev and uat, but they both use invoice ids from the same set.  The id is used when charging the person as a unique reference.  uat is well ahead of dev, so when we run the tests in dev, if the coresponding invoive in uat was paypal, it will fail and complain we already used it.
this pr changes to use stripe, which has no such problem,  I just used a test card and customer which should hopefully be OK.
@rupertbates

use stripe instead of paypal for testing zuora subscribe call

---

src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

Supposedly, `abTest` is deprecated and `abTests` is the one we should be using (according to [this comment](https://github.com/guardian/acquisition-event-producer/blob/91ff314c2f22eac82f1e7594cee6a300e6681873/src/main/scala/com/gu/acquisition/model/ReferrerAcquisitionData.scala#L19)).
@Ap0c followed this advice in https://github.com/guardian/support-frontend/pull/997 when he changed the clientside model from `abTest: ?AcquisitionABTest` to `abTests: ?AcquisitionABTest[]`. But unfortunately there's a bit in the middle here in support-workers which was only looking at `abTest`.
This is why we haven't been getting A/B test data for recurring contributions for the last few months. (We've had component ids as a workaround, which is why we didn't prioritise fixing it til now)
@Mullefa can you …

Use abTests in ReferrerAcquisitionData

---

build.sbt
cloud-formation/src/templates/cfn-template.yaml
src/main/scala/com/gu/config/Configuration.scala
src/main/scala/com/gu/ophan/AcquisitionService.scala
src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala

Adds a third acquisition service (in addition to ophan and GA) - a kinesis stream.
This will initially be used for the contributions ticker calculation.
Note - a credentials provider is not required by the kinesis client if running in a lambda. But it is required in order to run the integration tests locally.

Send acquisition events to kinesis

---

build.sbt
src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala

That version of `support-model` uses a version of `aacquisition-event-producer` that removes the deprecated `abTest` field
https://github.com/guardian/support-libraries/pull/5
https://github.com/guardian/acquisition-event-producer/pull/43

Bump support-models and remove abTest

---

src/main/scala/com/gu/support/workers/encoding/Encryption.scala

So you don't need the region set in your environment (as an environment variable or in `~/.aws/config`)
This means integration tests will work locally without an `~/.aws/config` file

Set region in code

---

build.sbt

fix snyk issues in jackson-databind - [project in snyk](https://app.snyk.io/org/the-guardian-cuu/project/5d479173-6e0d-4567-82e3-0cace22de5e6/)
[**Trello Card**](https://trello.com/c/PM8I1TCU/253-snyk-vulnerabilities-payment-api-zuora-auto-cancel-support-works-support-frontend)
tested this in CODE works OK for recurring contribution should be fine then

update jackson to keep snyk happy and bump aws lib too

---

build.sbt
src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
src/test/scala/com/gu/support/workers/Fixtures.scala
src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

The current Digital Pack thank you emails (triggered from subscriptions-frontend) include the Zuora subscription number, but the versions of the email triggered via support-workers include the Zuora account number.
Longer term, I think it is worth revisiting whether we should be including any Zuora numbers/ids at all (since we want users to redeem their digital benefits via their identity account), but this PR preserves the existing behaviour for now.
[**Trello Card**](https://trello.com/c/BdMnVPuz/1811-thank-you-email-credit-debit-card)
Note that this PR relies on a support-models release.
* Use a new version of support-models
* Pass subscription number into emails (instead of account number)

Replace account number with subscription number in thank you email

---

build.sbt
src/main/scala/com/gu/support/workers/PreviewPaymentSchedule.scala
src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
src/main/scala/com/gu/zuora/ZuoraService.scala
src/test/scala/com/gu/support/workers/Fixtures.scala
src/test/scala/com/gu/support/workers/PreviewPaymentScheduleSpec.scala
src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala
src/test/scala/com/gu/zuora/Fixtures.scala
src/test/scala/com/gu/zuora/ZuoraSpec.scala

This PR allows us to preview a user's payment schedule before creating a new subscription. This will allow us to provide accurate billing information in thank you emails (for subscriptions products), which becomes more important in complex scenarios where promotions and discounts are involved. 
Note that the email updates which make use of this payment schedule will be added in a subsequent PR.
* Use latest version of support-models and pass payment schedule through as part of SendThankYouEmailState
* Add code for previewing invoices via Zuora's REST API
* Refactor CreateZuoraSubscription slightly to accommodate preview
* Add (and update) unit tests

Preview upcoming payments and pass information through to thank you email lambda

---

src/main/scala/com/gu/emailservices/ContributionEmailFields.scala
src/main/scala/com/gu/emailservices/DigitalPackEmailFields.scala
src/main/scala/com/gu/emailservices/EmailFields.scala
src/main/scala/com/gu/emailservices/SubscriptionEmailFieldHelpers.scala
src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
src/test/scala/com/gu/emailservices/SubscriptionEmailFieldHelpersSpec.scala
src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala

This PR uses the payment schedule added in https://github.com/guardian/support-workers/pull/168, to provide an accurate description of a user's payment schedule for the thank you email.
[**Trello Card**](https://trello.com/c/BdMnVPuz/1811-thank-you-email-credit-debit-card)
* Add helpers to describe pricing based on payment schedule
* Replace some to-dos and hardcoded values in the Digital Pack email with calculated values
* Add unit tests

Use payment schedule to provide accurate pricing info in email

---

build.sbt
src/main/scala/com/gu/salesforce/Salesforce.scala
src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala
src/test/scala/com/gu/salesforce/Fixtures.scala
src/test/scala/com/gu/salesforce/SalesforceSpec.scala
src/test/scala/com/gu/salesforce/SerialisationSpec.scala
src/test/scala/com/gu/support/workers/errors/SalesforceErrorsSpec.scala

We are asking for telephone number in the new digital pack checkout. When we make a request to create a new digital pack, if the user gives us their telephone number, we will include it in that request. We should make sure that telephone number is saved in salesforce, so that we can use it to contact them regarding their subscription if relevant. 
[**Trello Card**](https://trello.com/c/zcaNKssy/2156-make-sure-telephone-number-if-provided-makes-its-way-to-salesforce)
* Use new version of support-models https://github.com/guardian/support-libraries/pull/16
* When we create a new salesforce contact, if we have a telephone number for the user, then we add this too the contact too.

If we have a telephone number when creating a salesforce contact, add it too.

---

src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala

As of https://github.com/guardian/support-workers/pull/176/files, we send address data to Salesforce when creating a digital pack subscription or recurring contribution via `support-workers`.
Address changes do get synced from Salesforce to Zuora, but the details when a new contact is created do not, so we send the address details in the billToContact when making the [subscribe request to Zuora](https://www.zuora.com/developer/api-reference/#operation/Action_POSTsubscribe)
The checkout on subscribe.theguardian also does this. See: https://github.com/guardian/membership-common/blob/master/src/main/scala/com/gu/zuora/soap/writers/Command.scala#L245
[**Trello Card**](https://trello.com/c/9e2k1vw4/2221-send-billing-address-data-to-sf)
* Send address details in the billToContact block of the …

send address details in the request to zuora to create a subscription

---

src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
src/main/scala/com/gu/support/workers/exceptions/ZuoraCatalogException.scala
src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala
src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala

Now that there is a mapping that provides RatePlanIds here:
https://github.com/guardian/support-libraries/blob/master/support-models/src/main/scala/com/gu/support/catalog/Product.scala
We should get the RatePlanIds for digital pack from that mapping instead, and then it doesn't need to be maintained in `support-config`.
Then we can also do the same for print products. 
[**Trello Card**](https://trello.com/c/ofdmiV3O/2253-add-paper-product-types-to-support-models-config-to-support-config)
* Get mapping of ratePlanIds from Product when a ratePlanId is needed to create a digital pack

When creating digital pack subscriptions, get rate plan id from the Product mapping

---

src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala
src/main/scala/com/gu/support/workers/exceptions/ZuoraCatalogException.scala
src/main/scala/com/gu/zuora/ProductSubscriptionBuilders.scala

Reverts guardian/support-workers#180

Revert "When creating digital pack subscriptions, get rate plan id from the Product mapping"
