common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala, monthly-contributions/src/main/scala/com/gu/support/workers/encoding/CreatePaymentMethodStateDecoder.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala, monthly-contributions/src/main/scala/com/gu/support/workers/model/Contribution.scala, monthly-contributions/src/main/scala/com/gu/support/workers/model/State.scala, monthly-contributions/src/main/scala/com/gu/support/workers/model/User.scala, monthly-contributions/src/test/scala/com/gu/support/workers/CreatePaymentMethodStateDecoderSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/CreateSalesforceContactDecoderSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
This should make it easier to add other currencies at a later stage.
=> Pass Currency and Country into the step functions

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateSalesforceContact.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala, monthly-contributions/src/test/scala/com/gu/support/workers/CreatePaymentMethodSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala, project/Dependencies.scala
This will allow joined-up logging in lambdas
=> Add request id to states

cloud-formation/src/state-machine-retries.yaml
Should have tried to deploy this before merging...
=> Correct the structure of the Catch clause

build.sbt, cloud-formation/src/cfn-template.yaml, cloud-formation/src/lambdas/createPaymentMethodLambda.yaml, cloud-formation/src/lambdas/createSalesforceContactLambda.yaml, cloud-formation/src/lambdas/createZuoraSubscriptionLambda.yaml, cloud-formation/src/lambdas/failureHandlerLambda.yaml, cloud-formation/src/lambdas/sendThankYouEmailLambda.yaml, cloud-formation/src/state-machine-retries.yaml, common/src/test/scala/com.gu.config/ConfigSpec.scala
Fix a few problems which were causing the deploy to fail
=> Fix deploys

common/src/main/scala/com/gu/membersDataAPI/MembersDataService.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/UpdateMembersDataAPI.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/UpdateMembersDataAPISpec.scala
We discovered a few problems with the membership data api update, this fixes them.
=> Fix membership data api update

README.md, TODO.md
So that we remember to make improvements if/when Amazon improve step functions
=> Start list of workarounds for step functions missing features

common/src/main/scala/com/gu/zuora/model/response/Responses.scala, common/src/test/scala/com/gu/zuora/Fixtures.scala, common/src/test/scala/com/gu/zuora/SerialisationSpec.scala, common/src/test/scala/com/gu/zuora/ZuoraSpec.scala
To test the monthly contributor creation process with users who are paying in US dollars.
[**Trello Card**](https://trello.com/c/G1g2zhtG/700-test-3-us-recurring-spike-us-recurring-back-end-work)
=> Tests for US Dollar support

cloud-formation/src/cfn-template.yaml, cloud-formation/src/lambdas/createZuoraSubscriptionLambda.yaml
There were a number of problems with the CloudFormation configuration which only showed up on deleting and recreating the stack. This PR fixes them.
=> Fixes for CloudFormation

common/src/main/scala/com/gu/helpers/FutureExtensions.scala, common/src/main/scala/com/gu/paypal/PayPalError.scala, common/src/main/scala/com/gu/salesforce/Salesforce.scala, common/src/main/scala/com/gu/stripe/Stripe.scala, common/src/main/scala/com/gu/support/workers/encoding/Encoding.scala, common/src/main/scala/com/gu/support/workers/encoding/ErrorJson.scala, common/src/main/scala/com/gu/support/workers/encoding/Wrapper.scala, common/src/main/scala/com/gu/support/workers/exceptions/RetryException.scala, common/src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala, common/src/main/scala/com/gu/support/workers/lambdas/Handler.scala, common/src/main/scala/com/gu/zuora/model/response/Responses.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ContributionCompleted.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ServicesHandler.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/ContributionCompletedSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala, project/Dependencies.scala
To provide immediate feedback to the customer so they know to try again now or later.
Also improves exception logging generally
=> Improved error handling

cloud-formation/src/build-cfn.js, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/ContributionCompleted.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
So we can create a cloudwatch dashboard of contributions
=> Add logging of successful and failed contributions

monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala
=> Ignore println style error in StateDecoder

common/src/test/scala/com/gu/zuora/Fixtures.scala, common/src/test/scala/com/gu/zuora/SerialisationSpec.scala, common/src/test/scala/com/gu/zuora/ZuoraSpec.scala, monthly-contributions/src/main/scala/com/gu/support/workers/encoding/StateDecoder.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala, monthly-contributions/src/test/scala/com/gu/support/workers/DefaultBillingPeriodSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/EndToEndSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala, monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/errors/PayPalErrorsSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala
To add a few tests for the two new currencies we are about to support Euros and Australian dollars.
I have also refactored some of the fixtures to reduce duplication.
[**Trello Card**](https://trello.com/c/WBxGnqcX/1000-add-zuora-support-for-euro-and-au-for-recurring-contributions)
=> Multi currency

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala, project/Dependencies.scala
To use the latest Thrift definitions (via acquisition-event-producer)
=> Upgrade workers and producer dependencies

monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala
To fix the tests.
* Fix country value in mock JSON input 
cc @michaelwmcnamara
=> Fix test JSON

common/src/main/scala/com/gu/zuora/encoding/CustomCodecs.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/PaymentMethodExtensions.scala, monthly-contributions/src/test/scala/com/gu/support/workers/Fixtures.scala, monthly-contributions/src/test/scala/com/gu/support/workers/WrapperSpec.scala, project/Dependencies.scala
To remove the code that was in place to handle old versions of the json input. This is not needed now that https://github.com/guardian/support-frontend/pull/390 has been merged.
I'm also now recording the payment method in the RequestInfo object.
=> Spring clean

common/src/test/scala/com/gu/salesforce/Fixtures.scala, common/src/test/scala/com/gu/zuora/Fixtures.scala, common/src/test/scala/com/gu/zuora/ZuoraSpec.scala
We recently deleted all of the test data in Zuora and Salesforce, which broke the integration tests. This PR fixes them by using fresh data.
=> Fix integration tests (use new data)

README.md
To improve the documentation (which will hopefully help people to save time and avoid making mistakes).
* Add some notes on the peculiarities of deploying a project based on Step Functions.
=> Add deployment information to README.md

common/src/main/scala/com/gu/helpers/WebServiceHelper.scala, common/src/main/scala/com/gu/salesforce/SalesforceService.scala, common/src/main/scala/com/gu/stripe/StripeService.scala, common/src/main/scala/com/gu/zuora/ZuoraService.scala, common/src/main/scala/com/gu/zuora/model/PaymentGateway.scala, common/src/test/scala/com.gu.config/ConfigSpec.scala, common/src/test/scala/com/gu/zuora/Fixtures.scala, common/src/test/scala/com/gu/zuora/PaymentGatewaySpec.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreatePaymentMethod.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala, project/Dependencies.scala
In order support payments through Stripe in Australian dollars we need to use a different account and Zuora Payment Gateway.
* Use new version of support-config to allow us to have different Stripe configs for Australia and the rest of the world.
* Use a different payment gateway for Stripe depending on the currency
=> New Stripe config

cloud-formation/src/templates/cfn-template.yaml
To notify the entire team if something goes wrong.
[trello card](https://trello.com/c/ndeIFgM2)
* updated the cfn.yaml
=> Updated alarms endpoints

common/src/main/scala/com/gu/emailservices/EmailService.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala
So that we can try to identify why the FailureHandler lambda is timing out.
[**Trello Card**](https://trello.com/c/Fh3vvzo7/1296-add-retries-to-cope-with-cases-where-failurehandler-throws-lambdaunknown-errors)
* Add a few log statements
=> Add logging to help with debugging

cloud-formation/src/templates/cfn-template.yaml
This alarm is not working as intended and is adding 0 value (see recent spam emails). 
I'd like to delete it whilst I think about better approaches to monitoring for this class of problem.
* Remove alert from Cloudformation
=> Delete glitchy alarm

monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
To ensure that we are collecting the debug information that we need / generally tidying up after myself.
=> Move log statement somewhere sensible

cloud-formation/src/templates/cfn-template.yaml, common/src/main/scala/com/gu/emailservices/EmailService.scala, common/src/main/scala/com/gu/zuora/ZuoraService.scala, common/src/main/scala/com/gu/zuora/model/response/PaymentMethodDetailResponse.scala, common/src/main/scala/com/gu/zuora/model/response/QueryResponse.scala, common/src/test/scala/com/gu/stepfunctions/StepFunctionsSpec.scala, common/src/test/scala/com/gu/zuora/ZuoraSpec.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala
To be legally compliant we need to send customers who sign up with Direct Debit a notification of the start of the agreement by email.
[**Trello Card**](https://trello.com/c/EnxDEHW7/1367-direct-debit-thank-you-email)
=> Direct Debit email

common/src/main/scala/com/gu/emailservices/EmailService.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala, monthly-contributions/src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala, monthly-contributions/src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala, monthly-contributions/src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala
Jon asked for some tweaks to the DD email.
=> Some tweaks to the Direct Debit email

build.sbt
Ensure that support-workers has zero security issues (according to Snyk).
[**Trello Card**](https://trello.com/c/sbht08n3/1570-ensure-that-snyk-has-zero-issues-on-all-sc-projects-support-workers)
=> Update dependencies to address vulnerabilities identified by Snyk

build.sbt, cloud-formation/src/templates/cfn-template.yaml, src/main/scala/com/gu/ophan/OphanService.scala, src/main/scala/com/gu/support/workers/exceptions/ErrorHandler.scala, src/main/scala/com/gu/support/workers/exceptions/RetryImplicits.scala, src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala
We want to send GA data from the server.
support-frontend [now sends through the relevant data](https://github.com/guardian/support-frontend/pull/1144)
[**Trello Card**](https://trello.com/c/2LzNAJax/147-serverside-ga-tracking-for-one-off-and-recurring-contributions)
=> Send GA data

src/main/resources/application.conf, src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala, src/main/scala/com/gu/zuora/ZuoraConfig.scala
The Digital Pack free trial period is implemented by setting the contract acceptance date to 16 days after the contract effective date (14 days free trial period plus a 2 day 'grace period').
This PR updates support-workers to use this method correctly
[**Trello Card**](https://trello.com/c/jAykcQi5/2069-set-the-correct-contract-acceptance-date-for-digital-pack-accounts-created-by-support-workers)
=> Digi pack acceptance date

build.sbt, scripts/pre-push, src/main/resources/application.conf, src/main/scala/com/gu/ophan/AcquisitionService.scala, src/main/scala/com/gu/services/Services.scala, src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala, src/main/scala/com/gu/zuora/model/response/Responses.scala, src/test/scala/com/gu/salesforce/Fixtures.scala, src/test/scala/com/gu/support/workers/EndToEndSpec.scala, src/test/scala/com/gu/support/workers/Fixtures.scala, src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala, src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala, src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala, src/test/scala/com/gu/support/workers/lambdas/SendAcquisitionEventSpec.scala, src/test/scala/com/gu/zuora/Fixtures.scala, src/test/scala/com/gu/zuora/SerialisationSpec.scala, src/test/scala/com/gu/zuora/ZuoraSpec.scala
A few of the integration tests had become broken due to recent changes, this PR fixes those tests or removes them where they are no longer needed. I have also added a pre-push git hook to make sure that the tests stay green in future.
[**Trello Card**](https://trello.com/c/sYEQ9kbt/2084-post-deploy-test-for-landing-pages)
=> Fix integration tests

src/test/scala/com/gu/support/workers/EndToEndSpec.scala, src/test/scala/com/gu/support/workers/JsonFixtures.scala, src/test/scala/com/gu/support/workers/WrapperSpec.scala, src/test/scala/com/gu/support/workers/errors/PayPalErrorsSpec.scala, src/test/scala/com/gu/support/workers/errors/StripeErrorsSpec.scala, src/test/scala/com/gu/support/workers/errors/ZuoraErrorsSpec.scala, src/test/scala/com/gu/support/workers/integration/CreateSalesforceContactSpec.scala, src/test/scala/com/gu/support/workers/integration/CreateZuoraSubscriptionSpec.scala, src/test/scala/com/gu/support/workers/integration/SendThankYouEmailSpec.scala, src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodSpec.scala, src/test/scala/com/gu/support/workers/lambdas/CreatePaymentMethodStateDecoderSpec.scala, src/test/scala/com/gu/support/workers/lambdas/CreateSalesforceContactDecoderSpec.scala, src/test/scala/com/gu/support/workers/lambdas/FailureHandlerSpec.scala, src/test/scala/com/gu/support/workers/lambdas/SendAcquisitionEventSpec.scala
There is also a class call Fixtures in this namespace in support-models and this causes problems with class resolution.
=> Rename the Fixtures class in com.gu.support.workers

build.sbt, src/main/scala/com/gu/support/workers/lambdas/CreateZuoraSubscription.scala, src/main/scala/com/gu/support/workers/lambdas/FailureHandler.scala, src/main/scala/com/gu/support/workers/lambdas/SendAcquisitionEvent.scala, src/main/scala/com/gu/support/workers/lambdas/SendThankYouEmail.scala
I need support-workers to be up to date with the latest versions in support-libraries to be able to move over to a mono repo.
=> Upgrade support-services to 0.12
